baseURL = 'https://ramalho.org/'
languageCode = 'pt-BR'
title = 'Blog do Ramalho.org'
theme = 'basico'

[markup.goldmark.renderer]
    unsafe = true

[markup.goldmark.renderHooks]
    image.enableDefault = true
    link.enableDefault = true

[markup]
  [markup.tableOfContents]
    startLevel = 2
    ordered = false
    endLevel = 2

# layout parameters

[params]
    width = "760px"
    custom_css = ["basico.css"]
