baseURL = 'https://ramalho.org/'
languageCode = 'pt-BR'
title = 'Blog do Ramalho.org'
theme = 'basico'
removePathAccents = true

[markup.goldmark.renderer]
    unsafe = true

[markup.goldmark.extensions.typographer]
    emDash = '&mdash;'


[markup.goldmark.renderHooks]
    image.enableDefault = true
    link.enableDefault = true

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

# layout parameters

[params]
    width = "760px"
    custom_css = ["basico.css"]

