baseURL = 'https://ramalho.org/'
languageCode = 'pt-BR'
title = 'Blog do Ramalho.org'
theme = 'basico'

[markup.goldmark.renderer]
    unsafe = true

[markup.goldmark.renderHooks]
    image.enableDefault = true
    link.enableDefault = true

# layout parameters

[params]
width = "760px"
